"""US Chart of Accounts template — GAAP-aligned, service / e-commerce focused."""

from __future__ import annotations

COA_TEMPLATE: list[dict] = [
    # ── Assets ───────────────────────────────────────────────────────────────
    {
        "code": "1000",
        "name": "Cash and Cash Equivalents",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
        "is_system": False,
    },
    {
        "code": "1010",
        "name": "Checking Account",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
        "parent_code": "1000",
    },
    {
        "code": "1020",
        "name": "Savings Account",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
        "parent_code": "1000",
    },
    {
        "code": "1100",
        "name": "Accounts Receivable",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
        "is_system": True,
        "is_control_account": True,
    },
    {
        "code": "1110",
        "name": "Allowance for Doubtful Accounts",
        "type": "asset",
        "subtype": "contra_asset",
        "normal_balance": "credit",
        "parent_code": "1100",
    },
    {
        "code": "1200",
        "name": "Prepaid Expenses",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
    },
    {
        "code": "1210",
        "name": "Prepaid Insurance",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
        "parent_code": "1200",
    },
    {
        "code": "1300",
        "name": "Inventory",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
    },
    {
        "code": "1500",
        "name": "Property, Plant & Equipment",
        "type": "asset",
        "subtype": "fixed_asset",
        "normal_balance": "debit",
    },
    {
        "code": "1510",
        "name": "Furniture & Fixtures",
        "type": "asset",
        "subtype": "fixed_asset",
        "normal_balance": "debit",
        "parent_code": "1500",
    },
    {
        "code": "1520",
        "name": "Computer Equipment",
        "type": "asset",
        "subtype": "fixed_asset",
        "normal_balance": "debit",
        "parent_code": "1500",
    },
    {
        "code": "1590",
        "name": "Accumulated Depreciation",
        "type": "asset",
        "subtype": "contra_asset",
        "normal_balance": "credit",
        "parent_code": "1500",
    },
    {
        "code": "1900",
        "name": "Other Assets",
        "type": "asset",
        "subtype": "other_asset",
        "normal_balance": "debit",
    },
    # ── Liabilities ───────────────────────────────────────────────────────────
    {
        "code": "2000",
        "name": "Accounts Payable",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
        "is_system": True,
        "is_control_account": True,
    },
    {
        "code": "2100",
        "name": "Accrued Liabilities",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
    },
    {
        "code": "2110",
        "name": "Accrued Wages",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
        "parent_code": "2100",
    },
    {
        "code": "2120",
        "name": "Accrued Interest",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
        "parent_code": "2100",
    },
    {
        "code": "2200",
        "name": "Sales Tax Payable",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
        "is_control_account": True,
    },
    {
        "code": "2300",
        "name": "Deferred Revenue",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
    },
    {
        "code": "2400",
        "name": "Short-Term Loans Payable",
        "type": "liability",
        "subtype": "current_liability",
        "normal_balance": "credit",
    },
    {
        "code": "2700",
        "name": "Long-Term Debt",
        "type": "liability",
        "subtype": "long_term_liability",
        "normal_balance": "credit",
    },
    {
        "code": "2900",
        "name": "Other Liabilities",
        "type": "liability",
        "subtype": "other_liability",
        "normal_balance": "credit",
    },
    # ── Equity ────────────────────────────────────────────────────────────────
    {
        "code": "3000",
        "name": "Owner's Equity",
        "type": "equity",
        "subtype": "equity",
        "normal_balance": "credit",
    },
    {
        "code": "3100",
        "name": "Common Stock",
        "type": "equity",
        "subtype": "equity",
        "normal_balance": "credit",
        "parent_code": "3000",
    },
    {
        "code": "3200",
        "name": "Additional Paid-In Capital",
        "type": "equity",
        "subtype": "equity",
        "normal_balance": "credit",
        "parent_code": "3000",
    },
    {
        "code": "3300",
        "name": "Retained Earnings",
        "type": "equity",
        "subtype": "equity",
        "normal_balance": "credit",
        "is_system": True,
    },
    {
        "code": "3400",
        "name": "Dividends / Distributions",
        "type": "equity",
        "subtype": "equity",
        "normal_balance": "debit",
    },
    # ── Revenue ───────────────────────────────────────────────────────────────
    {
        "code": "4000",
        "name": "Revenue",
        "type": "revenue",
        "subtype": "operating_revenue",
        "normal_balance": "credit",
    },
    {
        "code": "4010",
        "name": "Sales Revenue",
        "type": "revenue",
        "subtype": "operating_revenue",
        "normal_balance": "credit",
        "parent_code": "4000",
    },
    {
        "code": "4020",
        "name": "Service Revenue",
        "type": "revenue",
        "subtype": "operating_revenue",
        "normal_balance": "credit",
        "parent_code": "4000",
    },
    {
        "code": "4030",
        "name": "Subscription Revenue",
        "type": "revenue",
        "subtype": "operating_revenue",
        "normal_balance": "credit",
        "parent_code": "4000",
    },
    {
        "code": "4100",
        "name": "Sales Discounts",
        "type": "revenue",
        "subtype": "contra_revenue",
        "normal_balance": "debit",
    },
    {
        "code": "4200",
        "name": "Sales Returns & Allowances",
        "type": "revenue",
        "subtype": "contra_revenue",
        "normal_balance": "debit",
    },
    {
        "code": "4900",
        "name": "Other Income",
        "type": "revenue",
        "subtype": "other_revenue",
        "normal_balance": "credit",
    },
    {
        "code": "4910",
        "name": "Interest Income",
        "type": "revenue",
        "subtype": "other_revenue",
        "normal_balance": "credit",
        "parent_code": "4900",
    },
    {
        "code": "4920",
        "name": "FX Gain",
        "type": "revenue",
        "subtype": "other_revenue",
        "normal_balance": "credit",
        "is_system": True,
        "parent_code": "4900",
    },
    # ── Expenses ──────────────────────────────────────────────────────────────
    {
        "code": "5000",
        "name": "Cost of Goods Sold",
        "type": "expense",
        "subtype": "cogs",
        "normal_balance": "debit",
    },
    {
        "code": "5010",
        "name": "Direct Materials",
        "type": "expense",
        "subtype": "cogs",
        "normal_balance": "debit",
        "parent_code": "5000",
    },
    {
        "code": "5020",
        "name": "Direct Labor",
        "type": "expense",
        "subtype": "cogs",
        "normal_balance": "debit",
        "parent_code": "5000",
    },
    {
        "code": "5030",
        "name": "Subcontractors",
        "type": "expense",
        "subtype": "cogs",
        "normal_balance": "debit",
        "parent_code": "5000",
    },
    {
        "code": "6000",
        "name": "Operating Expenses",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
    },
    {
        "code": "6010",
        "name": "Salaries & Wages",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6020",
        "name": "Payroll Taxes",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6030",
        "name": "Employee Benefits",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6100",
        "name": "Rent & Occupancy",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6110",
        "name": "Utilities",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6200",
        "name": "Marketing & Advertising",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6300",
        "name": "Professional Services",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6310",
        "name": "Legal Fees",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6300",
    },
    {
        "code": "6320",
        "name": "Accounting & Audit",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6300",
    },
    {
        "code": "6400",
        "name": "Technology & Software",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6410",
        "name": "Cloud & Hosting",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6400",
    },
    {
        "code": "6500",
        "name": "Travel & Entertainment",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6600",
        "name": "Depreciation Expense",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6700",
        "name": "Insurance",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6800",
        "name": "Office Supplies",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "6900",
        "name": "Miscellaneous Expense",
        "type": "expense",
        "subtype": "operating_expense",
        "normal_balance": "debit",
        "parent_code": "6000",
    },
    {
        "code": "7000",
        "name": "Other Expenses",
        "type": "expense",
        "subtype": "other_expense",
        "normal_balance": "debit",
    },
    {
        "code": "7010",
        "name": "Interest Expense",
        "type": "expense",
        "subtype": "other_expense",
        "normal_balance": "debit",
        "parent_code": "7000",
    },
    {
        "code": "7020",
        "name": "FX Loss",
        "type": "expense",
        "subtype": "other_expense",
        "normal_balance": "debit",
        "is_system": True,
        "parent_code": "7000",
    },
    {
        "code": "7030",
        "name": "Bank Charges",
        "type": "expense",
        "subtype": "other_expense",
        "normal_balance": "debit",
        "parent_code": "7000",
    },
    {
        "code": "9000",
        "name": "Suspense / Clearing",
        "type": "asset",
        "subtype": "current_asset",
        "normal_balance": "debit",
        "is_system": True,
    },
]

DEFAULT_TAX_CODES: list[dict] = [
    {"code": "EXEMPT", "name": "Tax Exempt", "kind": "both", "rate": "0.00"},
    {"code": "SALES_TAX", "name": "Sales Tax (placeholder)", "kind": "sales", "rate": "0.00"},
]
